language: java

jdk:
  - openjdk8
  - openjdk11

install: mvn install -DskipTests -Dgpg.skip -B
script: mvn test -Dmaven.skip.deploy=true -B

after_success:
  - bash <(curl -s https://codecov.io/bash)